package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, October 3, 2011 1:27:55 AM GMT-08:00
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
   */
  public static final short value = (short)(2);
}
